
[package]
name = "stock_valuation_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas"] }
ndarray-stats = "0.5.1"
num = "0.4.3"
statrs = "0.17.1"
nalgebra = "0.32.6"
unit-root = "0.6.0"
linregress = "0.5.3"
rand = "0.8.5"
rand_distr = "0.4.3"
anyhow = "1.0.86"
rustimization = "*"
finitediff = "0.1.4"
openblas-src = "0.10.9"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
argmin = "0.10.0"
argmin-math = { version = "0.4.0", features = ["ndarray_latest", "nalgebra_latest"] }
